### ISSUE TITLE
Profile Information

### ISSUE THREAD

**Issue by tigransimonyan** [ananay/passport-apple#14]
Hello. 

Maybe you can parse the "decodedIdToken" as profile Information.
```js 
profile.provider = 'apple';
profile.id = decodedIdToken.sub;
profile.emails = [{ value: decodedIdToken.email }];
profile.displayName = decodedIdToken.email
        .replace(/@.+|\s|\+|\-|\_/, '')
        .replace(/\./, ' ');

```

**Comment by fega** [comment]
I'm also not getting the name, as stated in the docs. basically profile is empty

**Comment by peritbezek** [comment]
The profile information is actually sent by Apple, in the **user** post parameter, to your callback. There is, however, a gotcha like many Apple stuff. The user data is provided only in the first login attempt, or sign up attempt to be precise. On following calls, Apple does not send it again. In the case that your backend has failed to capture this information, the only way to get it again is the user removing the site from iCloud and doing the sign up thing again.
Here is a forum discussion link about this issue: [https://developer.apple.com/forums/thread/119826](url)

**Comment by ananay** [comment]
The last comment answered it correctly! Thanks @peritbezek.

This is also mentioned in the README.
