### ISSUE TITLE
Can I get the id_token in passport-apple?

### ISSUE THREAD

**Issue by ken0010072001** [ananay/passport-apple#17]
I saw that the apple sign in [tokenresponse](https://developer.apple.com/documentation/sign_in_with_apple/tokenresponse) have id_token(JWT).
but I find that  passport js only return (req, accessToken, refreshToken, decodedIdToken, profile, cb). 
are there any way to get the JWT?

**Comment by ananay** [comment]
Hi @ken0010072001 is there a particular reason why you want the JWT? I can look into it and add that feature if it's really necessary but trying to figure out what's the use case

**Comment by mmstart007** [comment]
@ananay I am getting an error in Apple login using passport-apple.

{"error":{"message":"Unable to verify authorization request state."}}

Could you please guide me to figure out ?

**Comment by iyromanov** [comment]
I also vote for passing JWT id_token to callback. My backend api accepts the JWT.

**Comment by krymson24** [comment]
Hi @ananay -- are there plans to address this? I believe what I've seen in other `passport` packages is that they return the `id_token`. Happy to help and make the change, if necessary!

**Comment by ananay** [comment]
@krymson24 @iyromanov Sounds cool!
@krymson24 thanks, please make a PR and I'll take a look! 🙌🏻

**Comment by krymson24** [comment]
@ken0010072001 @iyromanov @ananay PR up!
