### ISSUE TITLE
Retrieve user data

### ISSUE THREAD

**Issue by nicokaiser** [ananay/passport-apple#2]
Currently, only an ID is returned (idToken.sub) to identify the user.

In the future, it should be possible to retrieve the user's `email` and `name` properties (maybe through OAuth scopes), however is is neither documented by Apple yet, nor does the Sign in with Apple service return anything more than the ID.

This is also mentioned in ananay/apple-auth#8.

**Comment by nicokaiser** [comment]
I tried implementing retrieval of email and name properties in this module, but I could not add this for a couple of reasons:

- `email` is submitted inside the ID Token (JWT). Currently the module returns the `sub` property (which is the User ID) only. With the way passport-oauth2 works it is not possible to return additional data. It is possible to return an object, but that would be an incompatible change and more like a hack than anything.
- passport-oauth2 is not made for profile retrieval without calling an additional userInfo endpoint. In this case however, profile information is already there, but cannot be passed through to populate the result of the (empty) userInfo function.
- Retrieving the User `name` actually works, but is submitted alongside the authorization code, and only with `response_mode=form_post`, which is not supported at all by passport-oauth2.

So, I wrote a new version, which is more or less a simplified version of passport-oauth2 with support for Apple‘s non-standard endpoints: https://www.npmjs.com/package/@nicokaiser/passport-apple

**Comment by hansemannn** [comment]
Good thoughts @nicokaiser, I was having the same issues with receiving the profile. If Apple doesn't provide a profile endpoint like Facebook (via Graph) or Google (via REST API) do, the only way to receive it is from the native side (iOS 13+) is used. From the app, I don't even know if there is any chance right now.

**Comment by nicokaiser** [comment]
@hansemannn Did you have a look at my version of the library? It does receive the full profile (name (firstName, lastName), email).

**Comment by hansemannn** [comment]
I will now. Any reason it's not published to GitHub so far?

**Comment by nicokaiser** [comment]
@hansemannn There is a repo: https://github.com/nicokaiser/passport-apple (But you are right, it is not linked in the package.json yet, I'll change that).

**Comment by ananay** [comment]
All done and fixed! Kudos to @MotazAbuElnasr
Please install v1.1 and above for this :)
