### ISSUE TITLE
Why response_type, scope and response_mode are not in options ?

### ISSUE THREAD

**Issue by moninm** [ananay/passport-apple#20]
Strategy.prototype.authorizationParams = function (options) {
    options.state = options.state || crypto.randomBytes(5).toString('hex');
    options.response_type = "code id_token";
    options.scope = "name email";
    options.response_mode = "form_post";
    return options;
}

I wanted to use "query" response_mode and "form_post" is hardcoded.

**Comment by ananay** [comment]
form_post is what Apple's API expects in order to give you any sensitive user info (last I checked) which is why this is hardcoded
