### ISSUE TITLE
Anyone elses sign in with apple broken out of the blue lately? 

### ISSUE THREAD

**Issue by sebastiangug** [ananay/passport-apple#23]
I've been trying to get sign in with apple working using this package for two days now, it worked in development well but after trying to add the reply_url for production to test in the cloud, it stopped working in all placed, untouched. I have documented the configuration I did right here: 

https://stackoverflow.com/questions/66587045/passport-apple-inexplainable-invalid-client-on-nodejs-backend-using-clean-exa

Since then, I've also checked upon a previous application I developed that had sign in with apple using passport-apple working for months, untouched. and it is currently also broken.

**Comment by ananay** [comment]
@sebastiangug 
Did it stop working in development too? I feel this is a configuration error because the actual thing is working live on my website:

https://passport-apple.ananay.dev

**Comment by ananay** [comment]
@sebastiangug 
Please make this change in your Return URLs section and make sure there is only ONE URL in here.

![image](https://user-images.githubusercontent.com/5569219/110879115-a5e83d80-8299-11eb-8a71-89944403d457.png)

Also, please make sure your configuration is consistent with this guide: https://github.com/ananay/apple-auth/blob/master/SETUP.md

All the best, you got this! 💪🏻

**Comment by sebastiangug** [comment]
Yep, development stopped working too after removing & adding back the exact same reply-url.

Also, the apple interface for reply-urls doesn't look like that anymore :( 

I really believe this is an apple bug at this point, I have went even more vanilla than your passport package:  https://stackoverflow.com/questions/66591137/sign-in-with-apple-invalid-client-on-the-first-redirect-to-apple-of-the-oauth2

With the exact same results :( are you on a discord/slack group by any chance? I've been pestering others for a single set of temporary credentials (just client id + teamid + redirect_uri that has been added in their app) to see if my existing samples go further in the flow, although at this point i'm 99.9999% there's absolutely nothing wrong with the package. 

I've looked at the encryption algorithm for jwt, the expiry date being in seconds, made the expiry date 2 months to make sure some localisation on my machine doesn't make the token expire in over 6 months which is the apple limit, and none of it made any difference.

**Comment by ananay** [comment]
Sorry that you've had to struggle so much with this! Send me an email to
***@***.*** and then we can connect on Discord or something.

- Ananay

**Comment by sebastiangug** [comment]
Sadly the email doesn't show up in github, no worries though as I've just identified and fixed the issue. 

We now have to click on the left side of the apple dashboard on "more" and configure "email sources", instead of domain verification, without this, invalid_client seems to be thrown deceptively early in the process. Screens attached: 

![image](https://user-images.githubusercontent.com/27768313/110930125-aaa40480-8320-11eb-8b32-4eadef134d06.png)
![image](https://user-images.githubusercontent.com/27768313/110930271-cd361d80-8320-11eb-9ea8-1f38310ccef2.png)

The SPF must also be green for this to work. 

This also means there's no way to proxy an  inexisting domain to localhost for dev testing on our machines, only domains that are registered and have valid SPF.
