### ISSUE TITLE
'invalid_grand' error

### ISSUE THREAD

**Issue by RomanSolianik** [ananay/passport-apple#3]
Hello,

I'm trying to implement Sign in with Apple.
Here is my config (note, I don`t have config/config.json file, all variables is taken from the env):

```
 passport.use(new AppleStrategy({
            clientID: env.app.auth.apple.clientId,
            teamID: env.app.auth.apple.teamId,
            callbackURL: env.app.auth.apple.callbackUrl,
            keyID: env.app.auth.apple.keyId,
            privateKeyLocation: env.app.auth.apple.keyLocation,
        }, (accessToken, refreshToken, idToken, profile, done) => {
            // Here, check if the idToken exists in your database!
            done(null, idToken);
        }));
```

I am able to login as user in the apple page, but when apple is redirecting me back to the callbackURL I get the TokenError with 'invalid_grand' code.

Any idea what it wrong? Seems like application is configured properly in apple.

When I change the keyID, or private key itself, apple send 'invalid_client' error.

**Comment by RomanSolianik** [comment]
found what was wrong. It is redirectURI (callback). Configured values (callbackURL) is not working properly.

**Comment by ananay** [comment]
@RomanSolianik Really sorry for the confusion in the docs, this is correct on the repo – https://github.com/ananay/passport-apple-example

I've fixed it in the documentation. Thank you so much for letting me know!

**Comment by ananay** [comment]
@RomanSolianik I'm not sure what seems to be the issue here. "callbackURL" should be the parameter that should work for you – that is the one being used in the example as well. Please do not use the configuration file – redirect_uri is the one that should not work for you.

**Comment by RomanSolianik** [comment]
I was using 

`callbackURL: env.app.auth.apple.callbackUrl,`

but it does not work as expected. I set up the full URL

`https://55872656.ngrok.io/login/apple/callback`

but it sends request to apple with the following URL:

`http://55872656.ngrok.io/login/https://55872656.ngrok.io/login/apple/callback`

so ok, here I can fix it in the query param manually, but later I got the 'invalid_grant' because it sends request to get token with this incorrect callbackURL. I think it is the issue

**Comment by ananay** [comment]
Hi @RomanSolianik, I've just launched v1.1 of this repository and updated the README. Please feel free to comment on this issue or open another one if you find any other bugs.

If you need help with the implementation, here is a working version of passport-apple: https://github.com/ananay/passport-apple-example

Live here: https://passport-apple.ananay.dev
