### ISSUE TITLE
Name of user isn't transmitted (just email)

### ISSUE THREAD

**Issue by merganon** [ananay/passport-apple#31]
I realized that only the email of the user is transmitted, but not name (first and last name) of the user, even if the user logs in for the first time. "Profile" variable is also empty.

I thought it was fixed: https://github.com/ananay/passport-apple/issues/2#issuecomment-634703191

Is this intentional?

**Comment by ananay** [comment]
Interesting. [apple-auth](https://github.com/ananay/apple-auth) is able to do it, but unsure why this repo isn't able to get it. I'll look into it – thanks for letting me know!

**Comment by santychuy** [comment]
Any update on this?

**Comment by marcorm** [comment]
Same problem here...

**Comment by cchacholiades** [comment]
+1 Same here, profile does not include user first and last name (on first time login), any updates?

**Comment by ClockworkFTW** [comment]
Any updates?

**Comment by ananay** [comment]
Sorry for the *extremely* long delay on responding to this. You can use `req.body.user` to get the user's first name as soon as they register on the website. I've added this to my example too and in the README as well.

https://github.com/ananay/passport-apple-example/blob/master/src/index.js#L33

Feel free to reopen this incase of any questions!

Thanks!
