### ISSUE TITLE
Is there a case where `idToken` is not decoded?

### ISSUE THREAD

**Issue by 5d-jh** [ananay/passport-apple#32]
I passed all the parameters properly, however in verify function, I receive `idToken` as a plain string.

```typescript
new Strategy(
  {
    clientID: env.df,
    teamID: env.teamId,
    callbackURL: env.callbackUri,
    keyID: env.keyId,
    privateKeyString: env.privateKeyString.replace(/\\n/g, '\n'),
  },
  (accessToken, refreshToken, idToken /* <- this is just a plain string */, profile, done) => {
    
  },
);
```

**Comment by ultimate-tester** [comment]
According to the README, you are supposed to get it as a string which should be JWT decoded by yourself.
The problem I am having, is that I receive the refreshToken as the idToken, which I'm looking into now...

**Comment by 5d-jh** [comment]
@ultimate-tester This seems little bit out of topic but have you tried set `passReqToCallback` to `false`? After this I checked all the parameters passed properly.

**Comment by yepMad** [comment]
I'm facing this. instead of idToken I get a refresh token, or something else random

**Comment by ananay** [comment]
Hey, sorry for the delay in responding to this. I'm unable to replicate this issue or see this here: [passport-apple.ananay.dev](https://passport-apple.ananay.dev/)

Please check out the example repo here: github.com/ananay/passport-apple-example

**Comment by ananay** [comment]
Looks like everything looks good here – closing! Please feel free to open incase anything changes here. Thanks!
