### ISSUE TITLE
internal oauth error failed to obtain access token 

### ISSUE THREAD

**Issue by vthanhduc** [ananay/passport-apple#33]
Hi , I use your library and when I implement your passport-apple its just push this error: internal oauth error failed to obtain access token so I can not get info user, can you help me ? Many thanks

 InternalOAuthError: Failed to obtain access token
    at Strategy.OAuth2Strategy._createOAuthError (/be-event-svc/node_modules/passport-oauth2  /lib/strategy.js:422:17)
    at /be-event-svc/node_modules/passport-oauth2/lib/strategy.js:177:45
    at _tokenGenerator.generate.then.catch (/be-event-svc/node_modules/passport-apple/src/st  rategy.js:101:13)

**Comment by MayheMatan** [comment]
i'm getting the same error.

**Comment by ananay** [comment]
Hi there, this looks like an error with your configuration. Please refer to [setup.md](https://github.com/ananay/apple-auth/blob/master/SETUP.md) for instructions on how to setup, and also the (example repo)[https://github.com/ananay/passport-apple-example]. Thanks!

**Comment by TIGeMi** [comment]
I also get this error because of missing _privateKeyLocation_ config. Add this and this issue is solved.
`privateKeyLocation: 'src/AuthKey_XXXXXXXXX.p8'`
