### ISSUE TITLE
Apple actually sends email on subsequent logins

### ISSUE THREAD

**Issue by nesro** [ananay/passport-apple#36]
Hello fellow developers,

As I am debugging our app, I found out that on the first login, Apple indeeds sends: name, email and "appleId" (idToken.sub).

But on subsequent logins, **Apple still sends email**, "appleId" (idToken.sub) but indeed a name is missing. 

This fact is slightly different from what is written in the README:

> ⚠️ Important note: Apple will only provide you with the name and email ONCE which is when the user taps "Sign in with Apple" on your app the first time. 

Since names are not so important and emails are crucial (users can ask for reset password), this information might be useful to someone.

If someone can confirm this, README could be updated.

Thanks,
Tomas

**Comment by ananay** [comment]
That's interesting, I remember it only sends "sub". I can look into this
and update the README accordingly if that's the behavior exhibited.
Thanks for filing an issue!

- Ananay

**Comment by ananay** [comment]
Thanks for opening this issue! This is infact true and looks like this is the new behavior implemented. I've reflected the readme accordingly.
