### ISSUE TITLE
Unable to Get idToken in response

### ISSUE THREAD

**Issue by Karthik91465** [ananay/passport-apple#38]
Hello I have tried using this plugin.
But after user login I am only getting state and code.
I am not getting idToken or id_token in response.
I am using the same example mentioned.

**Comment by dgyurics** [comment]
> Hello I have tried using this plugin. But after user login I am only getting state and code. I am not getting idToken or id_token in response. I am using the same example mentioned.

I am experiencing a similar issue. Any progress/resolution?

**Comment by joosepwong** [comment]
Yes. I have the same experience. the strategy always send "code" only in responseType, but from your live example, we can see there were "code id_token" in the responseType

**Comment by ananay** [comment]
Check out the example code here: https://github.com/ananay/passport-apple-example
Please let me know if you're still having issues after following this example!
