### ISSUE TITLE
Publish new version to npm

### ISSUE THREAD

**Issue by feimosi** [ananay/passport-apple#5]
Please release a new version on npm. There's been several changes that are still missing when using v1.0.0.

**Comment by ananay** [comment]
Apologies for the late reply, apparently I wasn't getting these notifications. There's a bug in this library, which I'll be fixing within the next week or so and once that is done, I'll be publishing it to npm. In the meantime, you can check out [apple-auth](https://github.com/ananay/apple-auth) which is currently working perfectly for Sign in with Apple.

**Comment by feimosi** [comment]
No problem, thanks for the reply. Eventually I ended up using:
https://github.com/nicokaiser/passport-apple

**Comment by MotazAbuElnasr** [comment]
@ananay Are you working on it? 
I have used the package and fixed the bugs, If you haven't worked on it I can open a pull request

**Comment by ananay** [comment]
@MotazAbuElnasr Thank you so much! Please open the PR! I would love to take a look :)

**Comment by ananay** [comment]
All done and merged! I highly appreciate it, the repository is now back up and working! Thank you so much @MotazAbuElnasr! 🙌🏻

@feimosi just published version 1.1 that fixes everything!
