### ISSUE TITLE
Getting error "Unable to verify authorization request state." when pass state: true as option

### ISSUE THREAD

**Issue by salman486** [ananay/passport-apple#50]
Hi, Thank you for the work you have done.

I am getting this error "Unable to verify authorization request state." Whenever I pass state: true as an option to Strategy. I need to pass it as true so that it keeps the session of the user but the problem is that it gives me this error.

```
passport.use(
  new AppleStrategy(
    {
      clientID: config.apple.clientId,
      teamID: config.apple.teamId,
      keyID: config.apple.keyId,
      privateKeyString: config.apple.privateKey,
      callbackURL: `${config.authUrl}/v2/auth/apple/callback`,
      passReqToCallback: true,
      state: true,
    },
    async (
      req: Request,
      accessToken: string,
      refreshToken: string,
      idToken: string,
      profile: any,
      cb: any
      // eslint-disable-next-line max-params
    ) => {
//    code here...
    }
  )
```

**Comment by salman486** [comment]
If anyone following it and having same issue. Removing state code from below fixed the issue for me.

`    options.state = options.state || crypto.randomBytes(5).toString('hex');`

<img width="843" alt="image" src="https://github.com/ananay/passport-apple/assets/72623659/3cb17bbd-1153-4573-8daf-2c99d990b522">

**Comment by salman486** [comment]
If anyone following it and having same issue. Removing state code from below fixed the issue for me.

`options.state = options.state || crypto.randomBytes(5).toString('hex');`

<img width="843" alt="image" src="https://github.com/ananay/passport-apple/assets/72623659/3cb17bbd-1153-4573-8daf-2c99d990b522">

**Comment by ananay** [comment]
`state` isn't supposed to be a boolean value. It's used as a CSRF (Cross-Site Request Forgery) protection mechanism. You can pass in a random string value, or not specify it at all. The strategy is working as intended
