### ISSUE TITLE
TypeError: AppleStrategy is not a constructor

### ISSUE THREAD

**Issue by geekpulp** [ananay/passport-apple#6]
As per the conversation on twitter. I'm getting an error when I launch my app:

passport.use( new AppleStrategy( {
                          ^
TypeError: AppleStrategy is not a constructor

**Comment by geekpulp** [comment]
I seem to have worked around this. This error only presents when I have .strategy on the end of it.

Here's an example of work vs not working.

**Working**
	LocalStrategy = require( "passport-local" ).strategy,
	FacebookStrategy = require( 'passport-facebook' ).strategy,
	AppleStrategy = require( 'passport-apple' ),

**Not working**
	LocalStrategy = require( "passport-local" ).strategy,
	FacebookStrategy = require( 'passport-facebook' ).strategy,
	AppleStrategy = require( 'passport-apple' ).strategy,

**Comment by ananay** [comment]
I'm sorry for this issue! I'm going to fix this soon!

**Comment by ananay** [comment]
Hi @geekpulp, thanks for sharing!
This is already documented in the README.md file and also used in the example repository below:
https://github.com/ananay/passport-apple-example
