### ISSUE TITLE
arrow functions not working

### ISSUE THREAD

**Issue by kfir2037** [ananay/passport-apple#7]
hi,
my nodejs version is 0.11.12 and it not support in arrow functions or JSON.parse().
do you have any solution?

**Comment by ananay** [comment]
I would highly suggest that you upgrade your Node.js version! Is there a specific reason why you're using that old version? The reason why I'm encouraging you to upgrade is not only because of more features but also because of many security patches that might be there.

**Comment by kfir2037** [comment]
We have a very big app running on this server, so now we are checking if
such an update to the node version whould couse us problems. But probebly
we wil do the update eventully.
Thanx for your answer.

If we are already talking, you should know that there are few bugs with the
repository. For example if i want to get the user details and not just
token after the authentication, i need to add "response_mode=form_post",
but if i do so i need to handle the response with POST instead of GET.

Thanx again.

בתאריך יום ו׳, 24 באפר׳ 2020, 05:53, מאת Ananay Arora ‏<
notifications@github.com>:

**Comment by ananay** [comment]
@kfir2037, this library is still under work to get every feature of Sign in with Apple running. In the meantime, you can check out github.com/ananay/apple-auth which is another repository of mine that runs without PassportJS. Consider using that!

**Comment by kfir2037** [comment]
Thank you

בתאריך יום ו׳, 24 באפר׳ 2020, 12:46, מאת Ananay Arora ‏<
notifications@github.com>:
